package com.openttd.network.constant;

/**
 * See network_internal.h for changes
 */
public class NetworkInternal {

	public enum NetworkLanguage {
		NETLANG_ANY,
		NETLANG_ENGLISH,
		NETLANG_GERMAN,
		NETLANG_FRENCH,
		NETLANG_BRAZILIAN,
		NETLANG_BULGARIAN,
		NETLANG_CHINESE,
		NETLANG_CZECH,
		NETLANG_DANISH,
		NETLANG_DUTCH,
		NETLANG_ESPERANTO,
		NETLANG_FINNISH,
		NETLANG_HUNGARIAN,
		NETLANG_ICELANDIC,
		NETLANG_ITALIAN,
		NETLANG_JAPANESE,
		NETLANG_KOREAN,
		NETLANG_LITHUANIAN,
		NETLANG_NORWEGIAN,
		NETLANG_POLISH,
		NETLANG_PORTUGUESE,
		NETLANG_ROMANIAN,
		NETLANG_RUSSIAN,
		NETLANG_SLOVAK,
		NETLANG_SLOVENIAN,
		NETLANG_SPANISH,
		NETLANG_SWEDISH,
		NETLANG_TURKISH,
		NETLANG_UKRAINIAN,
		NETLANG_AFRIKAANS,
		NETLANG_CROATIAN,
		NETLANG_CATALAN,
		NETLANG_ESTONIAN,
		NETLANG_GALICIAN,
		NETLANG_GREEK,
		NETLANG_LATVIAN,
		NETLANG_COUNT;

		public static NetworkLanguage valueOf(int id) {
			for (NetworkLanguage value : values()) {
				if (value.ordinal() == id) return value;
			}
			return NETLANG_ANY;
		}
	}

}
